### ISSUE TITLE
Unable to change account settings

### ISSUE THREAD

**Issue by awlck** [iftechfoundation/ifdb-suggestion-tracker#291]
(I hope this is the right place for technical trouble like this, but here goes...)

I seem to have run into an issue changing the settings on my IFDB account (yr91uzpd5kvzdgdy). I keep getting the „An error occurred updating the database“ error. I first noticed this trying to change my account e-mail (in which case I do receive a new activation e-mail, but „the activation code wasn’t found in the user database,“ and the existing e-mail continues working as usual), but the error occurs whenever I try to change any setting at all.
Other features, such as reorganizing my wish list or voting on reviews, don’t seem to be affected.

**Comment by dfabulich** [comment]
Hi! This isn't "supposed to be" the place for technical support on IFDB… ideally you would have emailed us at ifdbadmin@ifdb.org. Having said that, this was due to a bug that I introduced, and this _is_ the right place to file bug reports, so I worked on the bug, and I believe I've fixed it. We'll roll out the changes in a day or so.

If you'd like us to change your email address while you wait, please contact us at ifdbadmin@ifdb.org and we'll get you sorted.

Thanks!

**Comment by awlck** [comment]
Thanks for the prompt fix! The e-mail thing isn't particularly urgent for me, I'll just retry my changes in a few days.

I'll try to keep the e-mail thing in mind in case I run into any more errors in the future. Thanks again.

-- Adrian

**Comment by dfabulich** [comment]
The fix is live now.
