### ISSUE TITLE
Can't select game by TUID or IFID when editing Cross-References

### ISSUE THREAD

**Issue by lkcampbell** [iftechfoundation/ifdb-suggestion-tracker#300]
## Repro steps:
1. Find a game you would like to use in a cross-reference, and copy the TUID and IFID of the game. For my example, I am using _The Magpie Takes the Train_, which has a TUID of `wfs8b2nphpeqrnaq` and an IFID of `1382CE5F-959A-4B62-A926-2A48EF5D0676`
2. Edit the game listing of the other game in the cross reference. For my example I am using _Alias 'The Magpie'_.
3. Under the `Cross-References` section, click on the `Add a Link` button and select `Sequel to` in the drop down menu.
4. In the text box labelled `Step 1: Search for a game by title, IFID, or TUID:`, enter the TUID of the first game and click on the `Search` button.
5. In the text box labelled `Step 1: Search for a game by title, IFID, or TUID:`, enter the IFID of the first game and click on the `Search` button.

## Observed behavior:
![Screen Shot 2021-04-15 at 4 06 08 PM](https://user-images.githubusercontent.com/1774931/114948867-b8a7e200-9e04-11eb-86a5-980094b5f4e1.png)

![Screen Shot 2021-04-15 at 4 07 35 PM](https://user-images.githubusercontent.com/1774931/114948876-bc3b6900-9e04-11eb-96c2-299eff0d641b.png)

## Expected behavior:
_The Magpie Takes the Train_ should show up in both cases so I can select it as my cross-reference game.

**Comment by jtn20** [comment]
I've run into this, and seen it return incorrect results rather than none.

For instance, searching for `2xyccw3pe0uovfad` (the TUID of _[Spider and Web](https://ifdb.org/viewgame?id=2xyccw3pe0uovfad)_) does not return me _Spider and Web_, but does return _[Chicken and Egg](https://ifdb.org/viewgame?id=zsole7usixgh2uxr)_.

(The fact that _Chicken and Egg_ has a 'spoof' relationship to the wanted _Spider and Web_ feels like A Clue. But it's not as simple as "returns all works related to TUID" -- I discovered this while adding the same relationship for _[Spyder and Jeb](https://ifdb.org/viewgame?id=4c95azoxjqsuusem)_, and the _Select a Game_ search results now are the same as they were before I did that.)

**Comment by jtn20** [comment]
Looking at [gamesearchpopup.php](https://github.com/iftechfoundation/ifdb/blob/main/www/gamesearchpopup.php), I see it emits a query of the form https://ifdb.org/search?xml&searchfor=2xyccw3pe0uovfad. And that (and indeed a regular search for `2xyccw3pe0uovfad` on IFDB's search page) only returns _Chicken and Egg_. I guess that's coming from a full-text search of _Chicken and Egg_'s Description field (which contains `A pastiche of "<a game="2xyccw3pe0uovfad">Spider and Web</a>"`).

Since this is just a regular search, the usual keywords apply. So, entering `ifid:1382CE5F-959A-4B62-A926-2A48EF5D0676` into the cross-reference pop-up does return _The Magpie Takes the Train_. So this case could be 'fixed' by documenting the need to use the prefix in the game search pop-up.

However, I don't think the IFDB search has any way of searching by TUID at all (via prefix or otherwise) -- at least, I've not found one looking through [searchutil.php](https://github.com/iftechfoundation/ifdb/blob/main/www/searchutil.php) or [search](https://github.com/iftechfoundation/ifdb/blob/main/www/search). So I'm not sure how that ever worked (if it did).
