### ISSUE TITLE
Trying to load a save and getting "Quixe run: Error: Function returned undefined value. Function returned undefined value."

### ISSUE THREAD

**Issue by nukeop** [iftechfoundation/ifdb-suggestion-tracker#376]
Hi, I'm trying to play this game: https://ifdb.org/viewgame?id=aearuuxv83plclpl

When I save, and try to get back to my save, I get the following error message: `Quixe run: Error: Function returned undefined value. Function returned undefined value.`

I tried this on Brave, Safari, and Firefox on a Macbook, all latest and clean without any addons. Could you please let me know how I can attempt to solve or debug this?

**Comment by dfabulich** [comment]
It sounds like you're reporting an error on iplayif.com, which is where you can play Counterfeit Monkey online. iplayif.com is powered by Parchment, and so issues with iplayif.com should be reported at https://github.com/curiousdannii/parchment

And, indeed, this issue is already reported as https://github.com/curiousdannii/parchment/issues/133

Parchment, like IFDB, is a volunteer-run organization. Hopefully somebody will find time to fix this bug soon! If not, and you're interested in helping to debug the issue, you might have luck replying to the issue above and working with @curiousdanni to fix the bug yourself.

**Comment by nukeop** [comment]
Thanks for directing me, I'll take it up there.
