### ISSUE TITLE
Mod tools should obscure private messages and personal e-mail as much as possible

### ISSUE THREAD

**Issue by brirush84** [iftechfoundation/ifdb-suggestion-tracker#46]

**Comment by dfabulich** [comment]
This issue is broad, and each privacy mitigation itself needs discussion, so I'm splitting this up into other bugs, all labeled "moderation tools," "privacy," and "needs discussion":

#165 Remove user's email address from the moderator "new user registration" emails
#264 "User self-comments" report shows private messages
#265 Don't show email addresses to moderators on user list/search
#266 Spoilerize email addresses on individual adminops user profiles
