### ISSUE TITLE
Ratings histogram includes special reviews

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb-suggestion-tracker#471]
https://intfiction.org/t/ifdb-rating-miscounting/70140/1

**Comment by dfabulich** [comment]
[Milliways](https://ifdb.org/viewgame?id=33vo6hneh99pjd41) currently says its rating is based on "9 ratings," but its histogram says that there are 5 4-star reviews, 3 3-star reviews, and 2 2-star reviews, for a total of 10 ratings.

This is happening because the histogram query includes "special reviews." In this case, it's including the "From the author" review.

That's confusing; the histogram query should use the computed values from the gameRatings view, which excludes reviews that are embargoed, "omitted from average," or "special type" ("from the author.")
