### ISSUE TITLE
Search for games liked by a particular reviewer

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#63]

**Comment by qdacsvx** [comment]
This would work well if users could LIKE games. It would be easy to generate a list of games LIKEd by any member.

If we presume that grades like 3/5 represent quality ratings, it doesn't follow that a high rating corresponds to liking. I might like a game but rate it 2/5 due to poor quality. I might dislike a game but rate it 5/5 due to fine writing, good implementation and good design.

**Comment by brirush84** [comment]
I'm torn. On the one hand, having two sets of scores (ratings vs likes) is confusing. On the other hand, there are 5 star games I wouldn't recommend and 3 star games I would.  I lean a bit more towards not adding 'likes'.

**Comment by alice-blue** [comment]
IFDB doesn't spell out what a star rating is supposed to mean (how well-crafted it is, how much a player personally liked it, or how highly a player would recommend it to others).

It would be interesting to know about cases when there is a mismatch between quality and personal enjoyment, but I'm not sure how to set that up, given that people are probably already using star ratings to mean different things.

**Comment by dfabulich** [comment]
When I filed this, I didn't realize that you could click through to an author's profile, click their "all reviews and ratings" link and sort by "Highest Rated first" https://ifdb.tads.org/allreviews?sortby=hi&newSortBy.x=0&newSortBy.y=0&id=nufzrftl37o9rw5t&ratings=yes&tag=

I also don't think it makes sense to add a separate "like" system on top of ratings, so I'm going to close this out. (If someone wants to file a separate issue for adding "likes," feel free.)
